/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.dcreations.cncsimulator;

import ch.dcreations.cncsimulator.gui.GUI;
import javafx.application.Application;

/**
 * <p>
 * <p>
 *  Runs the CNC Viewer  Main Application
 * <p>
 *
 * @author Damian www.d-creations.org
 * @version 1.0
 * @since 2022-08-18
 */

public class App {

    /**
     * Main Function
     * @param args run Arguments
     */
    public static void main(String[] args) {
        Application.launch(GUI.class);
        //Application.launch(gui.getClass(), args);
    }
}
